### ISSUE TITLE
いいところ診断の結果に優しさを追加したい

### ISSUE THREAD

**Issue by Hiro-Ume** [Hiro-Ume/assessment#1]
以下の結果を追加したい

'{userName}のいいところは優しさです。あなたの優しい雰囲気や立ち振る舞いに多くの人が癒やされています。'

**Comment by Hiro-Ume** [comment]
これから対応します。

**Comment by Umekichi-hero** [comment]
動作確認はできましたが、検証でconsoleを見てみるとerrorが出ているようです。

**Comment by Hiro-Ume** [comment]
b7a6277e47f1db5487f3ebf0ada52f40dfcd1e8a にて対応しました。
